### ISSUE TITLE
Bug przy tworzeniu audiogramu

### ISSUE THREAD

**Issue by damiank207** [Zespol-Inz-2016/Serwis-Audiometryczny#7]
`ModelState` w `AudiogramController.cs` traktuje wartość `false` jako error przy właściwości `IsMusician`.

Nie wiedzieć czemu program chce validować tego checkboxa. `ModelState.IsValid` nie przepuści formularza dopóki się nie zaznaczy tego pola.

`ModelState.IsValid` nie powinien patrzeć na tą właściwość.

**Comment by KapibaraPiotr** [comment]
Nie wiem, coś zrobił, ale działa.
